### ISSUE TITLE
Process XML errors in validate/pack commands

### ISSUE THREAD

**Issue by justkeepquiet** [vezel-dev/novadrop#23]
Hi. When runningcommand validate/pack command, I would like to be able to get the XML filename in which there is an error.
For example like this:
```
Unhandled exception: System.Xml.XmlException: '<', hexadecimal value 0x3C, is an invalid attribute character. Line 12, position 44.
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributesAsync()
   at System.Xml.AsyncHelper.ReturnTrueTaskWhenFinishCoreAsync(Task task)
   at System.Xml.XsdValidatingReader._ReadAsync_Read(Task`1 task)
   at Vezel.Novadrop.Commands.ValidateCommand.<>c__DisplayClass0_0.<<-ctor>b__1>d.MoveNext() in F:\novadrop-master\src\tools\dc\Commands\ValidateCommand.cs:line 51
```

**Comment by alexrp** [comment]
```console
$ dotnet run -c Release pack eur DataCenter_Final_EUR.dat
Packing 'eur' to 'DataCenter_Final_EUR.dat'...
Packed 24849 data sheets in 00:00:59.8840064.

Abnormality-1.xml:
  [E] (1,2): Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 1, position 2.
```
